export const appwriteConfig = {
  APPWRITE_API_ENDPOINT: String(import.meta.env.VITE_APPWRITE_API_ENDPOINT),
  APPWRITE_PROJECT_ID: String(import.meta.env.VITE_APPWRITE_PROJECT_ID),
  APPWRITE_BUCKET_ID: String(import.meta.env.VITE_APPWRITE_BUCKET_ID),
  APPWRITE_DATABASE_ID: String(import.meta.env.VITE_APPWRITE_DATABASE_ID),
  APPWRITE_USERS_COLLECTION_ID: String(
    import.meta.env.VITE_APPWRITE_USERS_COLLECTION_ID
  ),
  APPWRITE_POSTS_COLLECTION_ID: String(
    import.meta.env.VITE_APPWRITE_POSTS_COLLECTION_ID
  ),
  APPWRITE_SAVES_COLLECTION_ID: String(
    import.meta.env.VITE_APPWRITE_SAVES_COLLECTION_ID
  ),

  APPWRITE_DEV_KEY: String(import.meta.env.VITE_APPWRITE_DEV_KEY),
};
